on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/maemon4095/satysfi:latest
    steps:
    - name: checkout satysfi
      uses: actions/checkout@v3
      with:
        repository: gfngfn/SATySFi
        path: satysfi

    - name: restore last build commit
      uses: actions/download-artifact@v3
      with:
        name: last-commit-id
        path: last-commit-id
      continue-on-error: true
    
    - name: load last build commit id into environment variable 
      run: test -f "last-commit-id" && export ID=$(cat last-commit-id) && echo "LAST_COMMIT_ID=${ID}" >> $GITHUB_ENV || echo "first build"
    
    - name: load head commit id into environment variable
      run: export ID=$(git rev-parse HEAD) && echo "HEAD_COMMIT_ID=${ID}" >> $GITHUB_ENV
      working-directory: satysfi

    - run: echo "LAST_COMMIT_ID == HEAD_COMMIT_ID? ${{ env.LAST_COMMIT_ID == env.HEAD_COMMIT_ID }}" 
    
    