on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: repo

      - name: build
        run: docker compose run site bash -c 'npm install && npm run build -- --base="/${{github.event.repository.name}}/"'
        working-directory: repo

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: repo/site/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2