on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: repo
      
      